version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - backend

    ports:
      - "5123:80"

    environment:
      ConnectionStrings__DbConnection: "Server=db;Database=TurtleDb;User=sa;Password=P@ssw0rd;TrustServerCertificate=True"

    # Links the app container to the db container
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - backend

networks:
  backend:
