// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurtleApi.Db;

#nullable disable

namespace TurtleApi.Migrations
{
    [DbContext(typeof(TurtleDbContext))]
    [Migration("20230608202949_RelationFix")]
    partial class RelationFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurtleApi.Db.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TurtleId")
                        .HasColumnType("int");

                    b.Property<int>("TurtleId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurtleId");

                    b.HasIndex("TurtleId1");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("TurtleApi.Db.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId1")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProgramId1");

                    b.HasIndex("State");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("TurtleApi.Db.Turtle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Turtles");
                });

            modelBuilder.Entity("TurtleApi.Db.Program", b =>
                {
                    b.HasOne("TurtleApi.Db.Turtle", null)
                        .WithMany("Programs")
                        .HasForeignKey("TurtleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurtleApi.Db.Turtle", "Turtle")
                        .WithMany()
                        .HasForeignKey("TurtleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turtle");
                });

            modelBuilder.Entity("TurtleApi.Db.Step", b =>
                {
                    b.HasOne("TurtleApi.Db.Program", null)
                        .WithMany("Steps")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurtleApi.Db.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("TurtleApi.Db.Program", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TurtleApi.Db.Turtle", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
